# k8s manifest
apiVersion: batch/v1
kind: Job
metadata:
  generateName: gaze-vit-2-
spec:
  ttlSecondsAfterFinished: 86400 # auto-garbage-collect after 24 h
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: gaze-vit-2
          image: cmatrubhutam/gaze-vit-2-img:v2
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Gi"
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: dataset
              mountPath: /workspace/dataset
          env:
            - name: WANDB_TAGS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['job-name']
          envFrom:
            - secretRef:
                name: wandb-secret
      volumes:
        - name: dataset
          persistentVolumeClaim:
            claimName: gaze-dataset-pvc