# k8s manifest
apiVersion: batch/v1
kind: Job
metadata:
  generateName: gaze-vit-2-
spec:
  ttlSecondsAfterFinished: 86400 # auto-garbage-collect after 24 h
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: gaze-vit-2
          image: cmatrubhutam/gaze-vit-2-img:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Gi"
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1