apiVersion: v1
kind: Pod
metadata: 
  name: shell
spec:
  restartPolicy: Never
  containers:
    - name: shell
      image: busybox
      stdin: true
      tty: true
      command: ["sh"]
      volumeMounts:
        - name: dataset
          mountPath: /workspace/dataset
  volumes:
    - name: dataset
      persistentVolumeClaim:
        claimName: gaze-dataset-pvc

