# @package _global_
trainer:
  loss:
    _target_: losses.ce_only.CE

data_pipeline:
  preprocess_gaze:
    _target_: utils.patch_gaze_masks.do_nothing
    _partial_: true
    patch_size: ["${patch_size}", "${patch_size}"]
